### ISSUE TITLE
Issue parsing h5file file in the function 'createClustering'

### ISSUE THREAD

**Issue by omkarchandra** [MaayanLab/prismexp#1]
f = h5.File(h5file, 'r')
expression = f['data/expression']
samples = list(f['meta/samples/geo_accession'])

Error: "Unable to open object (object 'samples' doesn't exist)"

It means the file, human_matrix.h5, does not contain the 'samples' object. How would you rectify this error? Updating the human_matrix.h5 file or changing the code?

**Comment by lachmann12** [comment]
Could you try downloading the file manually from the download page. Sometimes the programmatic download corrupts the file. https://maayanlab.cloud/archs4/download.html

**Comment by omkarchandra** [comment]
Error resolved using the file after manual download.
